services:
  web:
    # image: odoo:14
    build: .
    user: "root"
    depends_on:
      - db
    ports:
      - "8069:8069"      # Odoo web interface
      - "8072:8072"      # Odoo longpolling
    # environment:
    #   - HOST=db
    #   - USER=odoo
    #   - PASSWORD=odoo
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      # - ./entrypoint.sh:/mnt/entrypoint.sh
      # - ./config:/etc/odoo
      # - ./addons:/mnt/extra-addons
      # - ./core:/mnt/core
    # command: ["odoo", "-c", "/etc/odoo/servicedesk.conf"]
    # command: ["odoo", "-c", "/etc/odoo/servicedesk.conf", "-i", "base", "--stop-after-init"]
    # command: ["odoo", "-c", "/etc/odoo/odoo.conf", "-i", "base", "--stop-after-init"]

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data